name: Run tests on PR
on: pull_request

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Test with gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
